function name_script=create_fit_intensity(main_dirr_isodistort,...
                                          main_dirr,file_name,...
                                          atom_type,idx_mode,model_name,parent_info,...
                                          latpar,occ_factors,nm_inteval_script,...
                                          nm_plot_script,nm_load_script,...
                                          nm_res_script,nm_upres_script)

code_01 = fileread([main_dirr_isodistort,'aux/fit_01.m']);

name_script=['main_fit_',file_name];
name_code = [newline '% The original (parent) structure is:' newline ...
             '% space group #',num2str(parent_info{1,1}),' - ',parent_info{1,2} newline ...
             '% a, b, c, alpha, beta, gamma = ',num2str(parent_info{1,3}) newline newline ...
             '% The superstructure in question is:' newline ...
             '% ',model_name newline ...
             '% For further details look into the specific subscripts' newline newline];

dirr_code = ['% addidng directories to the top of MATLAB path' newline ...
             'addpath(''',main_dirr,''');' newline ...
             'addpath([''',main_dirr,''',''atomic_form_factor/'']);' newline ...
             'addpath([''',main_dirr,''',''atomic_positions/'']);' newline ...
             '% addpath([''',main_dirr,''',''atomic_intensity/'']);' newline ...
             'addpath([''',main_dirr,''',''aux_residual/'']);' newline ...
             'addpath([''',main_dirr,''',''plots/'']);' newline newline ...
             '%% ' newline];

ll=size(idx_mode,1);
modes_names='';
modes_code=['% starting values for the fit' newline ...
            'A0 = [1 101.6 2e-4]; % [global_scaling_factor photon_energy_keV extinction_parameter]' newline];
p_names='';
p_code=[newline '% allowed parameters to vary in the fit: 0 - fixed; 1 - variable' newline ...
        'B0 = [1 0 0];' newline];
for idx=1:ll
    uno=zeros(1,idx_mode{idx}(2));
    if size(idx_mode{idx},2)==3
        p_code=strrep(p_code,atom_type{idx_mode{idx}(3)},[atom_type{idx_mode{idx}(3)},'/',atom_type{idx}]);
        modes_code=strrep(modes_code,atom_type{idx_mode{idx}(3)},[atom_type{idx_mode{idx}(3)},'/',atom_type{idx}]);
    else
        modes_code=[modes_code,'% ',atom_type{idx},' modes' newline ...
                '% M',num2str(idx),' = [',num2str(uno),']*1e-2;' newline ...
                'M',num2str(idx),' = ((rand(1,',num2str(idx_mode{idx}(2)),...
                ')>0.5)*2-1).*rand(1,',num2str(idx_mode{idx}(2)),')*1e-2;' newline];
        modes_names = [modes_names,'M',num2str(idx)];
        p_code=[p_code,'% ',atom_type{idx},' modes' newline ...
                    'P',num2str(idx),' = [',num2str(uno+1),']*0;' newline];
        p_names = [p_names,'P',num2str(idx)];
    end
    if idx < ll
        modes_names = [modes_names,','];
        p_names = [p_names,','];
    end
    if size(idx_mode{idx},2)==3
        modes_names(end) = '';
        p_names(end) = '';
    end
end

parameter_code = [newline 'fitpar0 = [A0,',modes_names,'];' newline ...
                  'tofit = logical([B0,',p_names,']);' newline ];

upres_code = [newline nm_upres_script,'(fitpar0,tofit);' newline ...
              'pars=fitpar0(logical(tofit));' newline ...
              'disp([''performing fit with '',num2str(sum(tofit(:))),'' free parameter(s)''])' newline];

fit_code = [newline '%% fit' newline ...
            '% options = optimset(''PlotFcns'',@optimplotfval,''MaxFunEvals'',1e5,''MaxIter'',1e5);' newline ...
            'options = optimset(''PlotFcns'',@optimplotfval);' newline ...
            '[x,R1] = fminsearch(@',nm_res_script,',pars,options);' newline ...
            '% recovering the full structure of the fitting parameters variable' newline ...
            'fitpar = fitpar0; fitpar(tofit) = x;' newline newline];

plot_code=['%% plotting' newline  '% load and convert the data' newline ...
           '[Q,Iexp,sigIexp,Q0,~] = ',nm_load_script,';' newline ...
           '% supercell lattice parameters' newline ...
           'aa = ',sprintf('%6.4f',latpar(1)),';' newline ...
           'bb = ',sprintf('%6.4f',latpar(2)),';' newline ...
           'cc = ',sprintf('%6.4f',latpar(3)),';' newline newline...
           'occ = [',sprintf('%6.5f  ',occ_factors),'];' newline newline...
           '% evaluate the fit intensity' newline ...
           'Icalc = ',nm_inteval_script,...
           '(Q,aa,bb,cc,occ,fitpar(1),fitpar(2),fitpar(3),fitpar(4:end));' newline newline...
           '% plot' newline ...
           'plot_title = [''',file_name,' --- R1 = $'',sprintf(''%5.3f'',R1*100),''\%$''];' newline ...
           'saveflag = 0; % 0 - not saving; 1 - saving figures (if proper part uncommented)' newline ...
           nm_plot_script,'(Q0,Iexp,Icalc,fitpar,aa,bb,cc,plot_title,saveflag);' newline newline];
       
full_code=[code_01,name_code,dirr_code,modes_code,p_code,parameter_code,...
           upres_code,fit_code,plot_code];

% saving
full_name=[main_dirr,name_script,'.m'];
fid = fopen(full_name, 'w');
if fid < 0, error(['Cannot open file ',full_name]); end
fwrite(fid,full_code);
fclose(fid);
end